# Generated by Django 2.1.5 on 2019-07-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=120)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Project')),
            ],
        ),
    ]
