# Generated by Django 2.1.5 on 2019-07-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='project',
        ),
    ]
